### DISCUSSION TITLE
Decreasing the number of database connections with pooling

### DISCUSSION THREAD

**Discussion by zvfcs** [ldproxy/ldproxy#1014] [Configuration]
I'm trying to decrease the number of database connections, by setting the pool "shared" to "true". 

All my SQL providers has the same settings under "connectionInfo". Still, every provider uses 4 connections each. Am I missing something, in how this is supposed to work?

I also tried to set the "maxConnections" to 2  and "minConnections" to 1, but the result is always 4 connections.

**Comment by azahnen** [comment]
Could you post your connectionInfo?

**Comment by zvfcs** [comment]
It's like this for all the providers:
```
connectionInfo:
  connectorType: SLICK
  dialect: PGIS
  database: apidatabase
  host: apiserver-prod01.ba.local
  user: api_user
  password: This i my password!
  schemas:
  - api
```
