### DISCUSSION TITLE
GML output: Control the order of different xlink sequences

### DISCUSSION THREAD

**Discussion by Sverre-Iversen** [ldproxy/ldproxy#1096] [Configuration] [answered]
Its ok to configure one xlink seqence in GML. But when I have two different sequences, I cannot control in which order the sequences are displayed. Example from `<provider>`.yml:

```
      harundersokelse:
        sourcePath: /[lokalid=underspkt_fk]geotekniskborehullunders{primaryKey=lokalid}{sortKey=lokalid}
        type: OBJECT_ARRAY
        objectType: Link
        label: Geoteknisk borehullsundersøkelse
        properties:
          href:
            sourcePath: lokalid
            type: STRING
            label: Geoteknisk borehullsundersøkelse lokal-ID
            transformations:
              stringFormat: '{{value | prepend:''id''}}'
      undersomr:
        type: OBJECT
        objectType: Link
        label: Geoteknisk undersøkelse
        properties:
          href:
            sourcePath: opprinneliggeotekniskundersid
            type: STRING
            label: Geoteknisk undersøkelse lokal-ID
            transformations:
              stringFormat: '{{value | prepend:''id''}}'
```
This ends up with the following GML fragment (... after some renaming in the `<service>`.yml configuration):
![gml-fragment-xlinks](https://github.com/interactive-instruments/ldproxy/assets/1905113/19a85560-d8d2-489f-84e5-eeb033c29e5a)

Each tag is correctly defined, but the problem is that "undersOmr" xlink tag should NOT be displayed before the "harUndersøkelse" sequence because "undersOmr" is defined after "harUndersøkelse" in the provider configuration file. This GML will not validate because the displayed tag-order is not right.

Any ideas? Or is my provider yml not defined right?
