### DISCUSSION TITLE
can't find sources in V3.6.0

### DISCUSSION THREAD

**Discussion by FabianRechsteiner** [ldproxy/ldproxy#1151] [Configuration]
```
installed ldproxy v3.6.0 with docker image: iide/ldproxy:latest
with
    volumes:
      - ./ldproxy:/ldproxy/data
```

I have created the following folder structure according to the instructions inside my ldproxy folder:

- store
  - defaults
    - services.ogc_api.yml
  - entities
    - providers
      - avprodukt.yml
      - tg_wfs_av-yml
    - services
      - avprodukt.yml
      - tg_wfs_av-yml
     - users
       - admin.yml
  - ...
 - cfg.yml
 - ...

Is this correct?

While I can see the created services at http://localhost:7080/rest/services, no data was found, neither from the PostGIS database nor from the WFS service. I suspect that the sources are not correctly defined in the cfg.yml file.

What do I need to adjust?

**cfg.yml**

```
---
store:
  mode: RW
  sources:
  - type: FS
    content: ALL
logging:
  level: 'OFF'
  appenders:
    - type: console
      timeZone: Europe/Berlin
  loggers:
    de.ii: INFO
```

**providers/avprodukt.yml**

```
---
id: avprodukt
createdAt: 1705052057335
lastModified: 1705052057335
entityStorageVersion: 2
providerType: FEATURE
providerSubType: SQL
nativeCrs:
  code: 2056
  forceAxisOrder: LON_LAT
connectionInfo:
  database: postgres
  host: postgis
  user: tileserver
  password: asjgr3939rwhfrkhsdf
  schemas: [avprodukt]
sourcePathDefaults:
  primaryKey: objectid
  sortKey: objectid
types:
  vineyards:
    sourcePath: /avprodukt
```

**services/avprodukt.yml**

```
---
id: avprodukt
lastModified: 1705053118203
entityStorageVersion: 2
label: avprodukt
description: AV Daten aus PostGIS Datenbank
enabled: true
serviceType: OGC_API
api:
- buildingBlock: TILES
  enabled: false
  transformations:
    '*':
    - flatten: .
- buildingBlock: TILE_MATRIX_SETS
  enabled: true
- buildingBlock: FLATGEOBUF
  enabled: false
  transformations:
    '*':
    - flatten: .
- buildingBlock: CSV
  enabled: false
  transformations:
    '*':
    - flatten: .

```

**Comment by FabianRechsteiner** [comment]
**ldproxy LOG**
```
ldproxy  | INFO  [2024-02-16 10:24:48,192]                          - Started web server at http://localhost:7080  
ldproxy  | INFO  [2024-02-16 10:24:48,423]                avprodukt - Feature provider with id 'avprodukt' started successfully. (min connections=1, max connections=4, stream capacity=4)  
ldproxy  | INFO  [2024-02-16 10:24:48,939]               geodienste - Feature provider with id 'geodienste' started successfully.  
ldproxy  | INFO  [2024-02-16 10:24:49,062]                tg_wfs_av - Feature provider with id 'tg_wfs_av' started successfully.  
ldproxy  | INFO  [2024-02-16 10:24:49,188]                avprodukt - Service with id 'avprodukt' started successfully.  
ldproxy  | INFO  [2024-02-16 10:24:49,224]               geodienste - Service with id 'geodienste' started successfully.  
ldproxy  | INFO  [2024-02-16 10:24:49,249]                tg_wfs_av - Service with id 'tg_wfs_av' started successfully. 
```


I have adjusted the files according to the instructions provided at [DOC](https://github.com/interactive-instruments/ldproxy/blob/master/demo/vineyards/README.md).

However, I still unfortunately encounter the problem that the materialized views and tables in my schema 'avprodukt' are not automatically recognized.

**providers/avprodukt.yml**
```
---
id: avprodukt
entityStorageVersion: 2
providerType: FEATURE
providerSubType: SQL
connectionInfo:
  database: postgres
  host: postgis
  user: tileserver
  password: 5sdf4r4te4awr4tger63ge4
  dialect: PGIS
sourcePathDefaults:
  primaryKey: objectid
  sortKey: objectid
autoPersist: true
```

**services/avprodukt.yml**
```
id: avprodukt
entityStorageVersion: 2
serviceType: OGC_API
auto: true
autoPersist: true
```

What is wrong?

Thanks for your help

**Comment by cportele** [comment]
@FabianRechsteiner - In `providers/avprodukt.yml` try adding `auto: true` as well as `schemas: [ 'avprodukt' ]` in `connectionInfo`.

See https://docs.ldproxy.net/providers/feature/#configuration and https://docs.ldproxy.net/providers/feature/10-sql.html#connection-info.

**Reply by FabianRechsteiner** [reply]
Thank you very much for your help. With the additional parameters, all tables and materialized views in the 'avprodukt' schema are now being read.

```
---
id: avprodukt
entityStorageVersion: 2
providerType: FEATURE
providerSubType: SQL
connectionInfo:
  database: postgres
  host: postgis
  user: tileserver
  password: wer54s6e6ws8e34wfwe
  dialect: PGIS
  schemas: [ 'avprodukt' ]
  auto: true
sourcePathDefaults:
  primaryKey: objectid
  sortKey: objectid
nativeCrs:
  code: 2056
  forceAxisOrder: NONE
auto: true
autoPersist: true
```

However, the user `tileserver` only has access to the materialized views, even though the tables were also recognized as data sources. Because the user does not have permission to access the data, these tables are displayed without objects.
How is that possible?

![image](https://github.com/interactive-instruments/ldproxy/assets/43602650/0d3ed7af-c5d0-4e8b-ac6b-a5d32ff21f7c)

I also want to provide vector tiles for all my materialized views now. I'm not entirely clear on which directory and file I need to activate and configure the OGC API Tiles. Are the directories mentioned in the[ first post ](https://github.com/interactive-instruments/ldproxy/discussions/1151#discussion-6066256) correct, or is that referring to the old folder structure?

Thank you for your support.
