### DISCUSSION TITLE
ldproxy v4.0.0-SNAPSHOT: GML delivery does not work

### DISCUSSION THREAD

**Discussion by Sverre-Iversen** [ldproxy/ldproxy#1197] [Configuration] [answered]
I have converted to the new configuration and try to download the GML representation, but another identical tab pops up and no GML is produced. Any ideas?

![Screenshot 2024-04-15 092813](https://github.com/interactive-instruments/ldproxy/assets/1905113/fe92ac29-9059-4e55-9b89-6182ed0590b9)

Is this a configuration issue that is not handled by the automatic conversion (xtracfg)?

**Comment by cportele** [comment]
As far as I know, there were no deprecated elements in the GML building block. That is, there should be no migration issue. We have a number of configurations with GML and they were all migrated without issues.

It is also not clear to me, how the GML link can result in an HTML response of the resource as you have described.

Can you post the configuration of the GML building block after the conversion?

GML was generated correctly before the migration of the configuration in version 3.6?

**Reply by Sverre-Iversen** [reply]
```
>Can you post the configuration of the GML building block after the conversion?
# Top level before the collection section:
- buildingBlock: GML
  enabled: false
  conformance: NONE

# After the collection section:
collections:
  bunnsedimentkornstoroversikt:
    id: bunnsedimentkornstoroversikt
    label: "1.1.1) Bunnsediment (kornstørrelse) flate, oversikt - tilpasset datamodell"
    enabled: true
    extent:
      spatialComputed: true
    api:
    - buildingBlock: FEATURES_CORE
      enabled: true
      defaultPageSize: 100
      itemType: feature
    - buildingBlock: SORTING
      enabled: true
      included:
      - sedkornstorrelse
      - datauttaksdato
    - buildingBlock: HTML
      enabled: true
      defaultStyle: bunnsedimentkornstoroversikt
    - buildingBlock: GML
      enabled: true
      transformations:
        identifikasjon:
        - rename: app:identifikasjon
        identifikasjon.lokalid:
        - rename: app:lokalId
        identifikasjon.navnerom:
        - rename: app:navnerom
        identifikasjon.versjonid:
        - rename: app:versjonId
        datauttaksdato:
        - rename: app:datauttaksdato
        forstedigitaliseringsdato:
        - rename: app:førsteDigitaliseringsdato
        geometri:
        - rename: app:område
        sedkornstorrelse:
        - rename: app:sedKornstørrelse
        sedkornstorrelsenavn:
        - rename: app:sedKornstørrelseNavn
      applicationNamespaces:
        app: http://skjema.geonorge.no/SOSI/produktspesifikasjon/BunnsedimenterKornstorrelse/1.1
      defaultNamespace: app
      schemaLocations:
        app: http://skjema.geonorge.no/SOSI/produktspesifikasjon/BunnsedimenterKornstorrelse/1.1/BunnsedimenterKornstorrelse.xsd
      objectTypeNamespaces:
        KornstrFlate: app
        Identifikasjon: app
      featureCollectionElementName: gml:FeatureCollection
      featureMemberElementName: gml:featureMember
      gmlIdPrefix: id
      conformance: NONE

>GML was generated correctly before the migration of the configuration in version 3.6?
Yes it worked well
```
