### DISCUSSION TITLE
Versjon 4: Building block SORTING not working

### DISCUSSION THREAD

**Discussion by Sverre-Iversen** [ldproxy/ldproxy#1201] [API]
I am using version 4.0.0 and get an error on buildingBlock: SORTING

```
    - buildingBlock: SORTING
      enabled: true
      included:
      - ankringsforhold
      - datauttaksdato
```

![image](https://github.com/interactive-instruments/ldproxy/assets/1905113/35360acb-2b72-4e3f-9c37-fcfc129195c0)

Any ideas?
