### DISCUSSION TITLE
ldproxy4: Startup with no errors, but get a "HTTP Error 404: Not Found" in the browser

### DISCUSSION THREAD

**Discussion by Sverre-Iversen** [ldproxy/ldproxy#1205] [General]
When I start the docker service, the log  seams OK (see screen dump below), but I get a 404 error in the browser.
I run xtracfg to check syntax and structure with on errors.

cfg-file:
```
server:
  applicationConnectors:
    - type: http
      port: '7080'
  # adminConnectors:
    # - type: http
      # port: '7081'
  externalUrl: http://<mydomain>.ngu.no:7081/rest/services/ 
...
```
DEBUG [2024-04-17 09:54:57,278]                          
- Loaded entities and overrides

DEBUG [2024-04-17 09:55:59,053]                          
- accept text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
- 
DEBUG [2024-04-17 09:55:59,055]                          
- content-type Optional[ApiMediaType{type=text/html, label=HTML, parameter=html, fileExtension=html, qs=1000}]

DEBUG [2024-04-17 09:55:59,056]                          
- Client error, HTTP status 404, Request path /l2401-sverre.ngu.no:7081/rest/services/: HTTP 404 Not Found

![Screenshot 2024-04-17 090657](https://github.com/interactive-instruments/ldproxy/assets/1905113/bfdcb9a6-53b7-430d-9c9e-1aea0c42dd96)
![Untitled-1](https://github.com/interactive-instruments/ldproxy/assets/1905113/212e85cb-ae3f-49db-a1d0-a0038a6262bd)
