### DISCUSSION TITLE
suppress IP-addresses in request logging

### DISCUSSION THREAD

**Discussion by schmity** [ldproxy/ldproxy#1222] [Setup]
Hi, 
given my setup in cfg.yml as below, how can I suppress logging IP-addresses while keep logging requests? 

server:
  requestLog:
    type: classic
    timeZone: Europe/Berlin
    appenders:
      - type: file
        currentLogFilename: "/apps/log/requests.log"
        archive: true
        archivedLogFilenamePattern: "/apps/log/requests-%d.log.gz"
        archivedFileCount: 7
...

Best 
Sebastian

**Comment by cportele** [comment]
Hi @schmity,

ldproxy uses dropwizard, which uses logback, and the configuration options of those libraries apply. See the [dropwizard documentation](https://www.dropwizard.io/en/stable/manual/configuration.html#request-log). 

To omit the IP address, you have to change the type (remove `type: classic`), because the classic logger has a fixed layout. Then add a `logFormat` property that does not include the host or IP address. See the [logback documentation](https://logback.qos.ch/manual/layouts.html#logback-access) for details on the options.

For example:

```yaml
server:
  requestLog:
    timeZone: Europe/Berlin
    appenders:
      - type: file
        currentLogFilename: "./data/log/requests.log"
        archive: true
        archivedLogFilenamePattern: "./data/log/requests-%d.log.gz"
        archivedFileCount: 7
        logFormat: "%t{ISO8601} %r %s %b %D"
```
