### DISCUSSION TITLE
WFS FEATURE provider

### DISCUSSION THREAD

**Discussion by lucamoroz** [ldproxy/ldproxy#1274] [Setup]
Hi everyone, I am trying to setup ldproxy to map an existing WFS API to the OGC feature core json API.

I am using the WFS provider type as declared in the documentation: https://docs.ldproxy.net/providers/feature/50-wfs.html

```yaml
id: veneto-wfs
providerType: FEATURE
providerSubType: WFS
connectionInfo:
  version: 2.0.0
  gmlVersion: 3.2.1
  connectorType: HTTP
  uri: https://idt2.regione.veneto.it/idt/geo/wfs
  method: GET
```

but when I start the ldproxy I get the following error message:

`Cannot load 'entities/providers/veneto-wfs.yml', feature provider type not supported: WFS `

This is my folder structure:

```
.
├── config
│   └── ldproxy
│       ├── data
│       │   └── cfg.yml
│       └── store
│           └── entities
│               ├── defaults
│               │   └── services
│               │       └── ogc_api.yml
│               └── instances
│                   ├── providers
│                   │   └── veneto-wfs.yml
│                   └── services
│                       └── veneto-wfs.yml
└── docker-compose.yml
```

What am I doing wrong?

Please find attached the source code to replicate the issue.

[ldproxy.zip](https://github.com/user-attachments/files/17261004/ldproxy.zip)

Thank you for any help!

**Comment by cportele** [comment]
The WFS feature provider is not actively maintained (see the `main` badge on the [WFS provider page](https://docs.ldproxy.net/providers/feature/50-wfs.html)), so `minMaintenance` has to be set to `NONE` in `cfg.yml` to enable the module. See https://docs.ldproxy.net/application/20-configuration/80-modules.html#modules. 

See https://docs.ldproxy.net/references/modules.html for more details on the lifecycle of modules.

**Reply by lucamoroz** [reply]
Danke @cportele, that solved the issue.
I am still getting an error: 

`Collection 'rv:edifici_scolastici' has been disabled because its feature type was not found in the provider schema. `

but I do not understand if it is related to the WFS provider (that as far as I understand it is no longer maintained) or to my configuration, because if I visit the WFS capabilities ([GetCapabilities](https://idt2.regione.veneto.it/idt/geo/wfs?REQUEST=GetCapabilities)) I can see the rv:edifici_scolastici feature and I can describe it ([DescribeFeatureType](https://idt2.regione.veneto.it/idt/geo/wfs?request=DescribeFeatureType&typeName=rv:edifici_scolastici)).

This is my provider config:

```
id: veneto-wfs
providerType: FEATURE
providerSubType: WFS
connectionInfo:
  version: 2.0.0
  gmlVersion: 3.2.1
  namespaces:
    ave: http://rexample.com/ns/app/1.0
    wfs: http://www.opengis.net/wfs/2.0
    fes: http://www.opengis.net/fes/2.0
    gml: http://www.opengis.net/gml/3.2
    xsd: http://www.w3.org/2001/XMLSchema
    ows: http://www.opengis.net/ows/1.1
    xlink: http://www.w3.org/1999/xlink
    xsi: http://www.w3.org/2001/XMLSchema-instance
    rv: it.veneto.regione.idt
  connectorType: HTTP
  uri: https://idt2.regione.veneto.it/idt/geo/wfs
  method: GET
```

And this is my service config:

```
id: veneto-wfs
serviceType: OGC_API
label: OCG API
description: Veneto OCG API
apiValidation: NONE
collections:
  rv:edifici_scolastici:
    id: rv:edifici_scolastici
    label: Edifici Scolastici
    enabled: true
    api:
    - buildingBlock: FEATURES_CORE
      enabled: true
      itemType: feature
```

Logs (truncated):

```
ldproxy  | INFO  [2024-10-07 11:48:14,630]                          - Started web server at http://localhost:7080/  
ldproxy  | DEBUG [2024-10-07 11:48:14,719]                          - Loading overrides  
ldproxy  | DEBUG [2024-10-07 11:48:14,731]               veneto-wfs - Creating new pool.  
ldproxy  | DEBUG [2024-10-07 11:48:14,743]               veneto-wfs - HTTP GET request: /idt/geo/wfs?REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0  
ldproxy  | DEBUG [2024-10-07 11:48:14,743]               veneto-wfs - HTTP Headers: []  
ldproxy  | INFO  [2024-10-07 11:48:15,123]               veneto-wfs - Feature provider with id 'veneto-wfs' state changed: AVAILABLE  
ldproxy  | INFO  [2024-10-07 11:48:15,123]               veneto-wfs - Feature provider with id 'veneto-wfs' started successfully.  
ldproxy  | ERROR [2024-10-07 11:48:15,128]               veneto-wfs - Collection 'rv:edifici_scolastici' has been disabled because its feature type was not found in the provider schema. 
```

Do you think this is due to the WFS provider? Should I abandon the idea of relying on it to translate WFS to [OGC API Features](https://github.com/opengeospatial/ogcapi-features)?
