### DISCUSSION TITLE
Performance using GeoPackages as datasources

### DISCUSSION THREAD

**Discussion by StefanSchuhart** [ldproxy/ldproxy#1277] [Configuration]
Hi everyone,

I'm testing ldproxy to provide data via OGC api features. I am a little disappointed with the data retrieval because of the slow delivery. Running this query oaf/streets/collections/streets/items?f=json&limit=6000 to receive approximately 800 kB of data the query returns after multiple seconds ranging from 2s to 4s. Thats very slow and it gets even slower with more data. Also, it seems to me that the same query never benefits from a query cache or whatsoever, I'm used to, when running a DBMS like PostgreSQL.

I tested on an Azure VM with 2 CPUs and 8 GB of RAM. Its clear to me that this is not a sophisticated test. Are there an configuration options to speed up reading from Geopackages? Using Gepackages would be my preferred deployment method for ldproxy in container environments.

Here is a snippet from my provider configuration:

```yaml
---
id: streets
entityStorageVersion: 2
providerType: FEATURE
providerSubType: SQL
nativeCrs:
  code: 25832
  forceAxisOrder: LON_LAT
typeValidation: NONE
connectionInfo:
  dialect: GPKG
  database: streets.gpkg
  pool:
    maxConnections: -1
    minConnections: 1
    initFailFast: true
    initFailTimeout: 1
    idleTimeout: 10m
    shared: false
sourcePathDefaults:
  primaryKey: fid
  sortKey: fid
queryGeneration:
  chunkSize: 10000
  computeNumberMatched: true
types:
  streets:
    label: Streets HH
    type: OBJECT
    sourcePath: /streets_v10
    properties:
      id:
        sourcePath: fid
        type: INTEGER
      geometry:
        sourcePath: geom
        type: GEOMETRY
        role: PRIMARY_GEOMETRY
        geometryType: LINE_STRING
      max_speed:
        sourcePath: max_speed
        type: FLOAT
      truck_traffic_daily:
        sourcePath: truck_traffic_daily
        type: FLOAT
      car_traffic_daily:
        sourcePath: car_traffic_daily
        type: FLOAT
      traffic_settings_adjustable:
        sourcePath: traffic_settings_adjustable
        type: INTEGER
      road_type:
        sourcePath: road_type
        type: STRING
```
