### DISCUSSION TITLE
Trying to get VALUE_ARRAY to work

### DISCUSSION THREAD

**Discussion by maaattes** [ldproxy/ldproxy#669] [Configuration] [answered]
Hi,
I'm trying to replicate something like in this example https://www.ldproxy.nrw.de/topographie/collections/ax_bahnstrecke/items/DENWAT01D0007K35?f=html
Here, if there is more than one value for 'Streckennummer' the label shown multiple times.

In my PostgreSQL/PostGIS Database, the values for 'Streckennummer' are stored in an array like so: {16, 18, 19, 5}.
So my first educated guess was:

```yaml
…
types:
  bahnstrecke:
    sourcePath: /bahnstrecke
    type: OBJECT
    properties:
      nummerderbahnstrecke:
        sourcePath: nummerderbahnstrecke
        type: VALUE_ARRAY
        valueType: STRING
…
```
        
But it's still showing the values as strings:
![grafik](https://user-images.githubusercontent.com/52661914/172146363-dd2b3b6a-d5e6-40a1-9b0c-9d21a441df1b.png)

![grafik](https://user-images.githubusercontent.com/52661914/172146543-ec1db536-9710-41a2-8085-a67f97b03a1a.png)

In some automatically generated config files I've seen the parameter
```yaml
additionalInfo:
  multiple: "true"
```
but this isn't documented anywhere I think it should be true without quotations marks?
If I'm adding this to my config (without quotation marks) I'm getting
![grafik](https://user-images.githubusercontent.com/52661914/172150033-a4f475fc-b5ff-4b53-bc3d-ddade0a7d3a4.png)

Could you give me a hint what I'm missing?

**Comment by cportele** [comment, marked as answer]
Hi @maaattes, I guess you are using PostgreSQL arrays? If that is the case, these are currently not supported. We have this capability on the radar, but so far all databases with multiple values used joins and separate tables, so for now only those are supported.

If you had a table `bahnstrecke_nrb` with a foreign key reference `rid` to the bahnstrecke feature and an attribute `nrb` with a ´single NRB value, the configuration would look as follows: 

```yaml
…
types:
  bahnstrecke:
    sourcePath: /bahnstrecke
    type: OBJECT
    properties:
      nummerderbahnstrecke:
        sourcePath: '[id=rid]bahnstrecke_nrb/nrb'
        valueType: STRING
        type: STRING
        label: Nummer der Bahnstrecke
…
```

If the table `bahnstrecke_nrb` does not have a standard sort key column (by default `id`), you would also have to specify a sort key in the source path, e.g. `sourcePath: '[id=rid]bahnstrecke_nrb/nrb{sortKey=rid}'`.
