### DISCUSSION TITLE
How to handle none-unique table names in different schemas

### DISCUSSION THREAD

**Discussion by Sverre-Iversen** [ldproxy/ldproxy#742] [Configuration] [answered]
We want to have datasets from different schemas in the same service. The table names do not have unique names across the schemas.
Is there a possibility to identify a table with a schema prefix in the "providers -> types" section? Or can it be done in another way without changing the table names?

**Comment by azahnen** [comment, marked as answer]
Schema prefixes are not supported yet, feel free to submit a feature request.

If every type only uses tables from a single schema (or at least tables with names unique inside the type), you could set up multiple providers. Every collection in the service might actually use a different provider, by default the provider with the same id as the service is used. So your service configuration might look like this:

```yml
id: multi-provider
...
collections:
  type1:
    id: type1
    api:
    - buildingBlock: FEATURES_CORE
      featureProvider: provider1
      featureType: type
  type2:
    id: type2
    api:
    - buildingBlock: FEATURES_CORE
      featureProvider: provider2
      featureType: type
```

**Reply by Sverre-Iversen** [reply]
The solution you suggested worked - thanks :)

**Reply by Sverre-Iversen** [reply]
I was probably too quick. I get this error  "**Server Error with ID 921545e1c5837ae5: Error building the tile transformation context.**" when clicking the "Web map using the style" for the external provider. I have to debug a little more. I think I give up external provider for now. It renders nicely when showing individual collections, but not using "Styles to render the data in maps" - > "Web map using the style".

**Reply by Sverre-Iversen** [reply]
**External providers**

I build the service configuration based on the example from  [azahnen](https://github.com/azahnen).

My skeleton code for the provider below - the types-section is empty because of external providers:
```
id: <id-multi-provider>
entityStorageVersion: 2
providerType: FEATURE
featureProviderType: SQL
connectionInfo:
  host: <host>
  database: <database>
  user: <user>
  password: <pwd>
  schemas:
  - <schema-1>
  - <schema-2>
  - <schema-n>
sourcePathDefaults:
  primaryKey: lokalid
  sortKey: lokalid
nativeCrs:
  code: 4258
  forceAxisOrder: LON_LAT
defaultLanguage: no
typeValidation: NONE
<no-content>
```
Seems to work OK except for the "**Error building the tile transformation context.**" error (see above).
**Can somebody see whats wrong with my configuration?**
