### DISCUSSION TITLE
Missing references to Tile providers objects

### DISCUSSION THREAD

**Discussion by ghelle-fhh** [ldproxy/ldproxy#746] [Configuration] [answered]
Hello,

I was attempting to set up an API where only an MBTiles file is the provider and OGC API Features is not enabled, similar to the example on the demo site:
https://demo.ldproxy.net/openmaptiles

However I cannot seem to find any futher documentation or examples. It appears to be referenced in the documentation, but links lead to nowhere:

https://docs.ldproxy.net/services/building-blocks/tiles.html#tile-provider

**Comment by azahnen** [comment, marked as answer]
Hi, 
yeah, sorry, the docs are still work in progress and will be completely revised before the next release.
I found an example in the old german docs: https://github.com/interactive-instruments/ldproxy/blob/v3.2.4/docs/de/configuration/services/building-blocks/tiles.md#tile-provider-mbtiles

**Reply by cportele** [reply]
In addition to the TILES configuration as shown in the example, you need to disable the features-related building blocks that are enabled by default:

```yaml
- buildingBlock: COLLECTIONS
  enabled: false
- buildingBlock: FEATURES_CORE
  enabled: false
- buildingBlock: FEATURES_HTML
  enabled: false
- buildingBlock: GEO_JSON
  enabled: false
- buildingBlock: CRS
  enabled: false
```

**Reply by ghelle-fhh** [reply]
Vielen Dank! That did the trick and it's working as expected for me now.

**Reply by ghelle-fhh** [reply]
Following these directions worked, however now I have the issue that the URL Template and TiIling Scheme do not appear, and metadata is also listed as undefined.

Unfortunately I'm at a loss as to why.

See here:

https://deegree.germanywestcentral.cloudapp.azure.com/rest/services/raster-mbtiles/v1/tiles

I downloaded sample data from here:
https://data.maptiler.com/maps/


And my service configuration looks like this:

```
id: raster-mbtiles
lastModified: 1666776279699
entityStorageVersion: 2
label: raster-mbtiles
enabled: true
serviceType: OGC_API
api:
- buildingBlock: TILES
  enabled: true
  tileProvider:
    type: MBTILES
    filename: maptiler-satellite.mbtiles
- buildingBlock: COLLECTIONS
  enabled: false
- buildingBlock: FEATURES_CORE
  enabled: false
- buildingBlock: FEATURES_HTML
  enabled: false
- buildingBlock: GEO_JSON
  enabled: false
- buildingBlock: CRS
  enabled: false
- buildingBlock: QUERYABLES
  enabled: false
```

I can't seem to tell what else I'm missing.

**Reply by cportele** [reply]
It is also unclear to me, in particular since everything looks correct and complete in JSON, including the tiling scheme information: https://deegree.germanywestcentral.cloudapp.azure.com/rest/services/raster-mbtiles/v1/tiles?f=json. It looks as if there is an issue in preparing the HTML from the tile sets data. I will see, if I can spot any reason for the behaviour.

That the URL template is undefined and that the TileJSON link is broken is a result of no tile matrix set in the dropdown list. Using the correct URL, the TileJSON is available: https://deegree.germanywestcentral.cloudapp.azure.com/rest/services/raster-mbtiles/v1/tiles/WebMercatorQuad?f=tilejson.

**Reply by cportele** [reply]
I have found the problem. The behaviour occurs, if the spatial extent of the dataset could not be determined. Of course, that should not stop adding the tiling scheme to the dropdown box. So, this is an issue that we will fix. In addition, the extent can be included in the MBTiles metadata. I will create an issue.

As a temporary fix, a default extent to the services configuration can be added.

```yaml
defaultExtent:
  spatial:
    xmin: -180.0
    ymin: -85.0511288
    xmax: 180.0
    ymax: 85.0511288
  spatialComputed: false
  temporalComputed: false
```
