### DISCUSSION TITLE
buildingBlock: GML

### DISCUSSION THREAD

**Discussion by Sverre-Iversen** [ldproxy/ldproxy#861] [API] [answered]
I am trying to use the buildingBlock: GML:
```
- buildingBlock: GML
  enabled: true
  applicationNamespaces:
    app: http://skjema.geonorge.no/SOSI/produktspesifikasjon/Gravbarhet/1.0
  schemaLocations:
    app: http://skjema.geonorge.no/SOSI/produktspesifikasjon/Gravbarhet/1.0/gravbarhet.xsd
  defaultNamespace: app
  featureCollectionElementName: gml:FeatureCollection
  featureMemberElementName: gml:featureMember
...
```
to get gml-data from postgres, but I get a strange "**FIX:ME**"-tag-error for the feature members.

GML-response:
```
<?xml version="1.0" encoding="utf-8"?>
<gml:FeatureCollection xmlns="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Gravbarhet/1.0" xmlns:app="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Gravbarhet/1.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Gravbarhet/1.0 http://skjema.geonorge.no/SOSI/produktspesifikasjon/Gravbarhet/1.0/gravbarhet.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd http://www.w3.org/1999/xlink http://www.w3.org/1999/xlink.xsd http://www.w3.org/XML/1998/namespace http://www.w3.org/2001/xml.xsd">
<gml:featureMember>
	<FIX:ME gml:id="00002f1b-37d7-4872-b801-eda4d3fb333e">
		<app:navnerom>https://data.geonorge.no/sosi/geologi/gravbarhet</app:navnerom>
		<app:versjonid>1.0</app:versjonid>
		<app:objekttype>GravbarhetFlate</app:objekttype>
		<app:gravbarhet>4</app:gravbarhet>
...
```
I know that the schema used won't validate the data, but why do I get the strange tag-name?

**Comment by cportele** [comment, marked as answer]
This happens, if there is no `objectType` specified for the feature type in the provider schema. 

For example:

```yaml
types:
  building:
types:
  building:
    label: Building
    sourcePath: /buildings
    type: OBJECT
    objectType: Building
    properties:
      ...
```

Then `Building` should be the element name. If the element is not in the default namespace (in your case it probably is), configure `objectTypeNamespaces` in the GML building block.

```yaml
  objectTypeNamespaces:
    building: ns2
```
