### DISCUSSION TITLE
Password Security

### DISCUSSION THREAD

**Discussion by ghelle-fhh** [ldproxy/ldproxy#870] [Configuration]
Hello,

we're planning on committing our ldproxy configs to a Bitbucket repo that only internal employees have access to. However, we are still are a concerned about having plain text passwords saved directly in the repository.

We explored simplying using environment variables, but given the fact that we have many databases we'd prefer not to introduce that complexity.

We also explored using defaults and marking those as ignored by git only to be saved on local machines, but we run into the same problem of extra complexity.

Any suggestions on a more elegant solution or best practice for this?

Many thanks!

**Comment by azahnen** [comment]
I think the complexity is part of the topic, you cannot really avoid it. You can only find solutions that provide the best usability for your workflow. I will give some suggestions below.

#### Case

I think defining variable substitutions in your configuration files is pretty much a given. I would strongly discourage from storing sensible data in configuration files, and variable substitutions tell ldproxy that these values will be provided by different means. 

A best practice would be to use variable names that are unique inside your organisation to prevent naming conflicts. Let's assume the following configuration:

```yml
connectionInfo:
  host: ${PROJECT3_PROVIDER11_DB_HOST:-server1}
  database: ${PROJECT3_PROVIDER11_DB_NAME:-db2}
  user: ${PROJECT3_PROVIDER11_DB_USER:-user4}
  password: ${PROJECT3_PROVIDER11_DB_PASSWORD}
```

Since in most cases you would not use the same database in production and development environments, I also defined variables with defaults for the non-sensible options. Of course you could also use overrides for these.

#### Production

##### Secrets

The best practice would be to use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) (or [Docker Secrets](https://docs.docker.com/engine/swarm/secrets/)) to provide variables to ldproxy:

```yml
apiVersion: v1
kind: Secret
metadata:
  name: project3-secrets
type: Opaque
stringData:
  PROJECT3_PROVIDER11_DB_HOST: server3
  PROJECT3_PROVIDER11_DB_NAME: db4
data:
  PROJECT3_PROVIDER11_DB_USER: YWRtaW4=
  PROJECT3_PROVIDER11_DB_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: project3-pod
spec:
  containers:
    - name: project3-ldproxy
      image: iide/ldproxy
      envFrom:
        - secretRef:
          name: project3-secrets

```

I also added the non-sensible data to the Secret, you could of course use ConfigMaps for that.

##### Vault

For a more advanced solution, you could use [Vault](https://www.vaultproject.io) or a similar Secrets Management System together with the [External Secrets Operator](https://external-secrets.io) which injects the Secrets into Kubernetes.

#### Development

I assume that in the development environment we are just running single containers with docker.

##### .env

Docker supports reading environment variables from files and passing them to containers. So we create a file `project3.env`

```yml
PROJECT3_PROVIDER11_DB_HOST: server5
PROJECT3_PROVIDER11_DB_NAME: db6
PROJECT3_PROVIDER11_DB_USER: admin
PROJECT3_PROVIDER11_DB_PASSWORD: cGFzc3dvcmQ=
```

 and pass it to `docker run`

```sh
docker run --env-file=project3.env iide/ldproxy
```

or use it in a `docker-compose.yml`

```yml
version: '3.8'

services:
  ldproxy:
    image: iide/ldproxy
    env_file:
      - project3.env
```

##### yml (future work)

There is a planned feature to define variables in the `cfg.yml` (no issue yet) and a feature scheduled for v3.4 to support multiple such files. That would allow a similar approach to `.env` files, but the variable names would be mapped to structured data, e.g. `secrets.yml`:

```yml
vars:
  project3:
    provider11:
      db:
        host: server5
        name: db6
        user: admin
        password: cGFzc3dvcmQ=
```

##### Vault (future work)

ldproxy could connect directly to Vault or similar and map variable names to Vault paths to request the required values on startup. Then you would of course still need an environment variable for your Vault credentials, but you would have reduced it to a minimum.
