### DISCUSSION TITLE
Config WFS via manager fails because server is behind proxy

### DISCUSSION THREAD

**Discussion by bstroebl** [ldproxy/ldproxy#947] [Setup] [answered]
Our Server is situated behind a proxy. Trying to configure a WFS service endpoint proxiing an external WFS from the internet fails with `org.apache.http.conn.ConnectTimeoutException: Connect to umweltgeodienste.schleswig-holstein.de:443 [umweltgeodienste.schleswig-holstein.de/141.91.161.254] failed: connect timed out`
The WFS is publicly available: https://umweltgeodienste.schleswig-holstein.de/WFS_KFUE?REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0
We are running a docker container and the container has a global proxy configured (tested with wget at the container's console).
How can we tell _ldproxy_ to use the global proxy setting or alternativly how to configure the proxy in _ldproxy_?

**Comment by azahnen** [comment, marked as answer]
Hi there,

I think global proxies are not supported, but you can configure a proxy in `cfg.yml`, for example:

```yaml
httpClient:
  proxy:
    host: 192.168.52.11
    port: 8080
    scheme : http
    auth:
      username: secret
      password: stuff
    nonProxyHosts:
      - '192.168.52.*'
```

This is not documented yet but I am pretty sure it works.
