### DISCUSSION TITLE
Hide certain properties in the configuration depending on output format

### DISCUSSION THREAD

**Discussion by Sverre-Iversen** [ldproxy/ldproxy#989] [Configuration] [answered]
Is it possible to hide certain properties in the configuration when a certain format (GML, GeoJSON,...) is displayed. Would be nice to hide in Link property (xlink) in GeoJSON or an "OGC API URL" property in GML. This can minimize the number of collection variants.

**Comment by cportele** [comment, marked as answer]
If you want to drop certain properties in a format, you can configure a `remove` transformation for the property in the building block of the format.

Here is an example from the [Vineyards API](https://demo.ldproxy.net/vineyards). The following removes the `village_info` from the vineyard features in the HTML representation; it is still included in other formats like GeoJSON (example: https://demo.ldproxy.net/vineyards/collections/vineyards/items/440403). `searchfield1` and `date` are only removed on the [items endpoint](https://demo.ldproxy.net/vineyards/collections/vineyards/items); the properties are still included in the HTML representation of a single feature.

```yaml
collections:
  vineyards:
    id: vineyards
    api:
    - buildingBlock: FEATURES_HTML
      transformations:
        village_info:
          remove: ALWAYS
        searchfield1:
          remove: IN_COLLECTION
        date:
          remove: IN_COLLECTION
```

[Source](https://github.com/ldproxy/demo/blob/main/store/entities/features/withTiles/services/vineyards.yml#L88-L97)
