### ISSUE TITLE
access control: cannot completely deny access for group `public`

### ISSUE THREAD

**Issue by azahnen** [ldproxy/ldproxy#1362]
### ldproxy Version

4.2.4

### Current Behavior

Setting `public: []` has no effect, the default `read` will be applied. That means the `public` will always have at least `discover` permissions.

### Expected Behavior

It is possible to completely deny access for group `public`.

### Steps to Reproduce

see above

### Relevant log output

```shell

```

**Comment by azahnen** [comment]
We added a special `noaccess` permission for this case:

```yml
accessControl:
  enabled: true
  groups:
    public:
      - noaccess
```
