### ISSUE TITLE
Incorrect evaluation of default feature property roles

### ISSUE THREAD

**Issue by cportele** [ldproxy/ldproxy#1412]
### ldproxy Version

4.3.2

### Current Behavior

In complex feature schemas, for example, those that make use of fragments, sometimes the roles `PRIMARY_INSTANT` or `PRIMARY_GEOMETRY` is assigned incorrectly.

An example:

```yaml
types:
  foo:
    sourcePath: /foo
    type: OBJECT
    label: foo
    properties:
      mydate:
        sourcePath: mydate
        type: DATE
    schema: "#/fragments/bar"
fragments:
  bar:
    type: OBJECT
    label: bar
    properties:
      start:
        sourcePath: bar_start
        type: DATETIME
        role: PRIMARY_INSTANT_START
      end:
        sourcePath: bar_end
        type: DATETIME
        role: PRIMARY_INSTANT_END
```

The result is that `mydate` gets the role `PRIMARY_INSTANT`. 

The reason are the check-methods in `FeatureSchema` that assign the role to the first temporal property, if there is no other temporal property with a temporal role. In the first ImmutableFeatureSchema that is built, the fragments have not yet been resolved, so the role `PRIMARY_INSTANT` is assigned to `mydate`. Since this is now explicitly set in the schema, the role is still kept, once the fragments are resolved with the primary interval properties.

### Expected Behavior

Only `start` and `end` have temporal roles.

### Steps to Reproduce

See above.

### Relevant log output

```shell

```
