### ISSUE TITLE
standard global configuration

### ISSUE THREAD

**Issue by cportele** [ldproxy/ldproxy#584]
If no `cfg.yml` file exists, ldproxy will create something like this when starting:

```yaml
---
server:
  applicationConnectors:
    - type: http
      port: '7080'
  adminConnectors:
    - type: http
      port: '7081'
  gzip:
    enabled: true
  requestLog:
    type: classic
    timeZone: Europe/Berlin
    appenders:
      - type: file
        currentLogFilename: "./data/log/requests.log"
        archive: true
        archivedLogFilenamePattern: "./data/log/requests-%d.log.gz"
        archivedFileCount: 7
  shutdownGracePeriod: 30s
httpClient:
  timeout: 30000ms
  connectionTimeout: 30000ms
logging:
  level: 'OFF'
  appenders:
    - type: file
      timeZone: Europe/Berlin
      currentLogFilename: "./data/log/xtraplatform.log"
      archive: true
      archivedLogFilenamePattern: "./data/log/xtraplatform-%d.log.gz"
      archivedFileCount: 7
      logFormat: "%-5p [%d{ISO8601,UTC}] %-48.48c{40}: %m%n%rEx"
  loggers:
    de.ii: INFO
```

Shouldn't we create a global configuration that looks more like this?

```yaml
---
logging:
  level: OFF
  appenders:
    - type: console
  loggers:
    de.ii: INFO
```
