### ISSUE TITLE
periodically analyze collection statistics

### ISSUE THREAD

**Issue by azahnen** [ldproxy/ldproxy#633]
Follow-up to #630.

Configuration proposal along the lines of `seedingOptions`:

```yml
api:
- buildingBlock: FEATURES_CORE
  analyzeStats:
    runOnStartup: true
    runPeriodic: '0 * * * *'
    maxThreads: 4
```
