### ISSUE TITLE
504 gateway timeout when adding a SQL service

### ISSUE THREAD

**Issue by codehub-rony** [ldproxy/ldproxy#647]
I have a postgres database in Azure with one spatial dataset. I'm running ldproxy in a Azure app service using a Dockerfile. This setup works fine. I can access ldproxy through the browser.

I run into problems when I try to connect to the postgres database. After filling in all the connection details and click `add`, the service starts loading. After 3-5 minutes however, I get a 504 gateway timeout response. The log does not show any errors in `debug` mode, only the following two lines: 
```
- Feature provider with id 'panden' is in auto mode, generating configuration ...
- rxjava2-jdbc - maxIdleTime: 0, healthCheck: POSTGRES,  idleTimeBeforeHealthCheck: 60
```
It seems as if the process of adding the service just freezes. I don't have this issue when connecting to the same database running ldproxy locally on my machine. Any thoughts on what might be causing this? 

This is my `cfg.yml`
```
---
store:
  mode: READ_WRITE
logging:
  level: "DEBUG"
  sqlQueries: ON
  stackTraces: ON
  appenders:
    - type: console
      timeZone: Europe/Berlin
      currentLogFilename: /ldproxy/log/ldproxy.log
      archive: false
      archivedLogFilenamePattern: /ldproxy/log/ldproxy-%d.zip
      archivedFileCount: 30
```
