### ISSUE TITLE
Support for PostgreSQL arrays 

### ISSUE THREAD

**Issue by cportele** [ldproxy/ldproxy#671]
### Describe the Feature Request

Support one-dimensional [PostgreSQL arrays](https://www.postgresql.org/docs/current/arrays.html) in the SQL feature provider for VALUE_ARRAY types.

### Describe the Use Case

This would support PostgreSQL databases that make use of columns with a numeric or text array. Note that in some cases GDAL also creates PostgreSQL schemas with such arrays. 

### Describe Preferred Solution

If `myarrayproperty` would be a `text[]` column, the property could be specified in the feature provider as:

```yaml
      myArrayProperty:
        sourcePath: myarrayproperty
        type: VALUE_ARRAY
        valueType: STRING
```

### Additional Information

See https://github.com/interactive-instruments/ldproxy/discussions/669.
